### ISSUE TITLE
virtocommerce/platform:latest container crashes after docker-compose up -d command

### ISSUE THREAD

**Issue by charlesansong** [VirtoCommerce/vc-docker#11]
When I run docker-compose up -d for vc-docker linux file, the platform immediately exists but the storefront and db keeps running. I have a 4GB Linux vps running Debian.

**Comment by AndrewEhlo** [comment]
We'll be back after testing the issue.

**Comment by charlesansong** [comment]
@AndrewEhlo Did you resolve the situation? Also I am trying to install Virtocommerce platform on say http://admin.store.com and storefront on http://store.com and then add SSL to these sites. How do I go about that?

**Comment by AndrewEhlo** [comment]
@charlesansong Sorry for the delayed reply.
I ran docker-compose up -d for the vc-docker linux file on my linux box, but didn't encounter the problem (using the `feat/net8` branch). 
In some cases, the VC platform pod may need to be manually restarted after the module installation process is complete, so you may have encountered this. 
As for the SSL certificate question, I recommend using a proxy server for SSL termination and letting the proxy server communicate with the pods via http.

**Comment by charlesansong** [comment]
What i really want is a step by step guide to installing virto platform
with domain https://admin.store.com and the storefront on https://store.com.
Then finally connect them using the string to have a fully functional
store. I have skills for Magento and others but not for .Net platforms like
this.

**Comment by AndrewEhlo** [comment]
There is no Virto Commerce specific configuration for using SSL, it's more an infrastructure configuration. Please follow the common approaches (e.g.: https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-8.0&tabs=linux-ubuntu#configure-nginx).
Another option is to use Virto Commerce Cloud for a fully maintained, highly available and secure infrastructure.
